spring.datasource.url=jdbc:mysql://reseau.proxy.rlwy.net:54517/railway?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=nxvEdBWhuGLQyDUnwLpAQcOWDBLkJwAs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=disable
spring.security.user.password=disable

server.port=8080